export const INCREMENT_ACTIVE_LINE = 'INCREMENT_ACTIVE_LINE'
export const DECREMENT_ACTIVE_LINE = 'DECREMENT_ACTIVE_LINE'

export const INCREMENT_ACTIVE_FILERUN = 'INCREMENT_ACTIVE_FILERUN'
export const DECREMENT_ACTIVE_FILERUN = 'DECREMENT_ACTIVE_FILERUN'

export const CODEFILES_RECIEVED = 'CODEFILES_RECIEVED'

export const FILERUNS_RECIEVED = 'FILERUNS_RECIEVED'

// -- newActionType_hook --
